spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rashen-db
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  application:
    name: taskService

server:
  port: 8081
eureka:
  instance:
    hostname: localhost